# Inventory line (1-6)
# 인벤토리 줄 (1-6)
line: 3
icon:
  11:
    difficulty: "peaceful"
    description: "Vanilla peaceful difficulty"
    item: "minecraft:nether_star"
  12:
    difficulty: "easy"
    description: "Vanilla easy difficulty"
    item: "minecraft:nether_star"
  13:
    difficulty: "normal"
    description: "Vanilla normal difficulty"
    item: "minecraft:nether_star"
  14:
    difficulty: "hard"
    description: "Vanilla hard difficulty"
    item: "minecraft:nether_star"
  15:
    difficulty: "hardcore"
    description: "Vanilla hardcore mode\nIt will remove your experience and inventory when you die"
    item: "minecraft:nether_star"
